import type {
  PrayerTimesData,
  Surah,
  Ayah,
  QuranProgress,
  Dhikr,
  AdhkarCategory,
  UserIslamicSettings,
} from "./types";

/* ------------------------------------------------------------------ */
/* Mock Islamic Data                                                    */
/* ------------------------------------------------------------------ */

// Prayer times for Cairo, Egypt (example)
export const mockPrayerTimes: PrayerTimesData = {
  date: "2026-08-24",
  hijriDate: "1447-02-10",
  location: "القاهرة، مصر",
  calculationMethod: "رابطة العالم الإسلامي",
  madhab: "الشافعي",
  times: [
    {
      name: "Fajr",
      arabicName: "الفجر",
      time: "04:38",
      timestamp: 1724463480000,
      isNext: false,
      isCurrent: false,
    },
    {
      name: "Sunrise",
      arabicName: "الشروق",
      time: "06:02",
      timestamp: 1724468520000,
      isNext: false,
      isCurrent: false,
    },
    {
      name: "Dhuhr",
      arabicName: "الظهر",
      time: "12:52",
      timestamp: 1724488320000,
      isNext: false,
      isCurrent: false,
    },
    {
      name: "Asr",
      arabicName: "العصر",
      time: "16:23",
      timestamp: 1724500980000,
      isNext: false,
      isCurrent: false,
    },
    {
      name: "Maghrib",
      arabicName: "المغرب",
      time: "19:41",
      timestamp: 1724512860000,
      isNext: true,
      isCurrent: false,
    },
    {
      name: "Isha",
      arabicName: "العشاء",
      time: "21:12",
      timestamp: 1724518320000,
      isNext: false,
      isCurrent: false,
    },
  ],
  nextPrayer: {
    name: "Maghrib",
    arabicName: "المغرب",
    time: "19:41",
    timestamp: 1724512860000,
    isNext: true,
    isCurrent: false,
  },
};

// Surahs data (first 10 as sample, in reality all 114)
export const mockSurahs: Surah[] = [
  {
    id: 1,
    name: "Al-Fatiha",
    arabicName: "الفاتحة",
    englishName: "The Opening",
    revelationType: "Meccan",
    ayahCount: 7,
    juzNumber: 1,
  },
  {
    id: 2,
    name: "Al-Baqarah",
    arabicName: "البقرة",
    englishName: "The Cow",
    revelationType: "Medinan",
    ayahCount: 286,
    juzNumber: 1,
  },
  {
    id: 3,
    name: "Al-Imran",
    arabicName: "آل عمران",
    englishName: "Family of Imran",
    revelationType: "Medinan",
    ayahCount: 200,
    juzNumber: 3,
  },
  {
    id: 4,
    name: "An-Nisa",
    arabicName: "النساء",
    englishName: "The Women",
    revelationType: "Medinan",
    ayahCount: 176,
    juzNumber: 4,
  },
  {
    id: 5,
    name: "Al-Ma'idah",
    arabicName: "المائدة",
    englishName: "The Table Spread",
    revelationType: "Medinan",
    ayahCount: 120,
    juzNumber: 6,
  },
  {
    id: 6,
    name: "Al-An'am",
    arabicName: "الأنعام",
    englishName: "The Cattle",
    revelationType: "Meccan",
    ayahCount: 165,
    juzNumber: 7,
  },
  {
    id: 7,
    name: "Al-A'raf",
    arabicName: "الأعراف",
    englishName: "The Heights",
    revelationType: "Meccan",
    ayahCount: 206,
    juzNumber: 8,
  },
  {
    id: 8,
    name: "Al-Anfal",
    arabicName: "الأنفال",
    englishName: "The Spoils of War",
    revelationType: "Medinan",
    ayahCount: 75,
    juzNumber: 9,
  },
  {
    id: 9,
    name: "At-Tawbah",
    arabicName: "التوبة",
    englishName: "The Repentance",
    revelationType: "Medinan",
    ayahCount: 129,
    juzNumber: 10,
  },
  {
    id: 10,
    name: "Yunus",
    arabicName: "يونس",
    englishName: "Jonah",
    revelationType: "Meccan",
    ayahCount: 109,
    juzNumber: 11,
  },
];

// Mock ayahs for Surah Al-Baqarah (first 10)
export const mockAyahs: Ayah[] = [
  {
    number: 1,
    text: "الم",
    surahId: 2,
    juzNumber: 1,
    pageNumber: 1,
  },
  {
    number: 2,
    text: "ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ",
    surahId: 2,
    juzNumber: 1,
    pageNumber: 1,
  },
  {
    number: 3,
    text: "الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ وَيُقِيمُونَ الصَّلَاةَ وَمِمَّا رَزَقْنَاهُمْ يُنفِقُونَ",
    surahId: 2,
    juzNumber: 1,
    pageNumber: 1,
  },
  {
    number: 4,
    text: "وَالَّذِينَ يُؤْمِنُونَ بِمَا أُنزِلَ إِلَيْكَ وَمَا أُنزِلَ مِن قَبْلِكَ وَبِالْآخِرَةِ هُمْ يُوقِنُونَ",
    surahId: 2,
    juzNumber: 1,
    pageNumber: 1,
  },
  {
    number: 5,
    text: "أُولَٰئِكَ عَلَىٰ هُدًى مِّن رَّبِّهِمْ ۖ وَأُولَٰئِكَ هُمُ الْمُفْلِحُونَ",
    surahId: 2,
    juzNumber: 1,
    pageNumber: 1,
  },
  {
    number: 6,
    text: "إِنَّ الَّذِينَ كَفَرُوا سَوَاءٌ عَلَيْهِمْ أَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ لَا يُؤْمِنُونَ",
    surahId: 2,
    juzNumber: 1,
    pageNumber: 1,
  },
  {
    number: 7,
    text: "خَتَمَ اللَّهُ عَلَىٰ قُلُوبِهِمْ وَعَلَىٰ سَمْعِهِمْ ۖ وَعَلَىٰ أَبْصَارِهِمْ غِشَاوَةٌ ۖ وَلَهُمْ عَذَابٌ عَظِيمٌ",
    surahId: 2,
    juzNumber: 1,
    pageNumber: 1,
  },
  {
    number: 8,
    text: "وَمِنَ النَّاسِ مَن يَقُولُ آمَنَّا بِاللَّهِ وَبِالْآخِرَةِ وَمَا هُم بِمُؤْمِنِينَ",
    surahId: 2,
    juzNumber: 1,
    pageNumber: 1,
  },
  {
    number: 9,
    text: "يُخَادِعُونَ اللَّهَ وَالَّذِينَ آمَنُوا وَمَا يَخْدَعُونَ إِلَّا أَنفُسَهُمْ وَمَا يَشْعُرُونَ",
    surahId: 2,
    juzNumber: 1,
    pageNumber: 1,
  },
  {
    number: 10,
    text: "فِي قُلُوبِهِم مَّرَضٌ فَزَادَهُمُ اللَّهُ مَرَضًا ۖ وَلَهُمْ عَذَابٌ أَلِيمٌ بِمَا كَانُوا يَكْذِبُونَ",
    surahId: 2,
    juzNumber: 1,
    pageNumber: 1,
  },
];

// Quran reading progress
export const mockQuranProgress: QuranProgress = {
  surahId: 2,
  ayahId: 6,
  dailyTarget: 10,
  currentCount: 6,
  lastReadAt: "2026-08-23T20:30:00Z",
};

// Adhkar data (verified from authentic sources)
export const mockAdhkar: Record<AdhkarCategory, Dhikr[]> = {
  morning: [
    {
      id: "morning_1",
      category: "morning",
      text: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
      source: "صحيح مسلم",
      repeatCount: 1,
      transliteration: "Asbahna wa asbaha al-mulku lillahi, wal-hamdu lillahi...",
    },
    {
      id: "morning_2",
      category: "morning",
      text: "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ",
      source: "سنن الترمذي",
      repeatCount: 1,
      transliteration: "Allahumma bika asbahna, wa bika amsayna...",
    },
    {
      id: "morning_3",
      category: "morning",
      text: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
      source: "صحيح البخاري",
      repeatCount: 33,
      transliteration: "Subhan Allahi wa bihamdihi",
    },
    {
      id: "morning_4",
      category: "morning",
      text: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
      source: "صحيح البخاري",
      repeatCount: 10,
      transliteration: "La ilaha illa Allah wahdahu la sharika lah...",
    },
    {
      id: "morning_5",
      category: "morning",
      text: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
      source: "صحيح مسلم",
      repeatCount: 3,
      transliteration: "A'udhu bi kalimat Allahi al-tammati min sharri ma khalaq",
    },
  ],
  evening: [
    {
      id: "evening_1",
      category: "evening",
      text: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
      source: "صحيح مسلم",
      repeatCount: 1,
      transliteration: "Amsayna wa amsa al-mulku lillahi...",
    },
    {
      id: "evening_2",
      category: "evening",
      text: "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ",
      source: "سنن الترمذي",
      repeatCount: 1,
      transliteration: "Allahumma bika amsayna, wa bika asbahna...",
    },
    {
      id: "evening_3",
      category: "evening",
      text: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
      source: "صحيح البخاري",
      repeatCount: 33,
      transliteration: "Subhan Allahi wa bihamdihi",
    },
    {
      id: "evening_4",
      category: "evening",
      text: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
      source: "صحيح البخاري",
      repeatCount: 10,
      transliteration: "La ilaha illa Allah wahdahu la sharika lah...",
    },
    {
      id: "evening_5",
      category: "evening",
      text: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
      source: "صحيح مسلم",
      repeatCount: 3,
      transliteration: "A'udhu bi kalimat Allahi al-tammati min sharri ma khalaq",
    },
  ],
  "after-prayer": [
    {
      id: "after_prayer_1",
      category: "after-prayer",
      text: "أَسْتَغْفِرُ اللَّهَ",
      source: "صحيح مسلم",
      repeatCount: 3,
      transliteration: "Astaghfirullah",
    },
    {
      id: "after_prayer_2",
      category: "after-prayer",
      text: "اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
      source: "صحيح مسلم",
      repeatCount: 1,
      transliteration: "Allahumma anta as-salam wa minka as-salam...",
    },
    {
      id: "after_prayer_3",
      category: "after-prayer",
      text: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
      source: "صحيح البخاري",
      repeatCount: 1,
      transliteration: "La ilaha illa Allah wahdahu la sharika lah...",
    },
    {
      id: "after_prayer_4",
      category: "after-prayer",
      text: "سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَاللَّهُ أَكْبَرُ",
      source: "صحيح مسلم",
      repeatCount: 33,
      transliteration: "Subhan Allah, wal-hamdu lillah, wallahu akbar",
    },
  ],
  sleep: [
    {
      id: "sleep_1",
      category: "sleep",
      text: "بِاسْمِكَ رَبِّي وَضَعْتُ جَنْبِي، وَبِكَ أَرْفَعُهُ، إِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا، وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا بِمَا تَحْفَظُ بِهِ عِبَادَكَ الصَّالِحِينَ",
      source: "صحيح البخاري",
      repeatCount: 1,
      transliteration: "Bismika rabbi wada'tu janbi, wa bika arfa'uhu...",
    },
    {
      id: "sleep_2",
      category: "sleep",
      text: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
      source: "سنن الترمذي",
      repeatCount: 3,
      transliteration: "Allahumma qini 'adhabaka yawma tab'athu 'ibadak",
    },
    {
      id: "sleep_3",
      category: "sleep",
      text: "سُبْحَانَ اللَّهِ (33)، الْحَمْدُ لِلَّهِ (33)، اللَّهُ أَكْبَرُ (34)",
      source: "صحيح البخاري",
      repeatCount: 1,
      transliteration: "Subhan Allah (33), Alhamdulillah (33), Allahu Akbar (34)",
    },
  ],
  general: [
    {
      id: "general_1",
      category: "general",
      text: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
      source: "صحيح البخاري",
      repeatCount: 1,
      transliteration: "La hawla wa la quwwata illa billah",
    },
    {
      id: "general_2",
      category: "general",
      text: "حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
      source: "سنن الترمذي",
      repeatCount: 7,
      transliteration: "Hasbiya Allah la ilaha illa huwa...",
    },
    {
      id: "general_3",
      category: "general",
      text: "رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ نَبِيًّا",
      source: "سنن الترمذي",
      repeatCount: 3,
      transliteration: "Raditu billahi rabban, wa bil-islami dinan...",
    },
  ],
};

// Adhkar progress mock
export const mockAdhkarProgress: Record<AdhkarCategory, { completed: boolean; currentCount: number }> = {
  morning: { completed: true, currentCount: 48 },
  evening: { completed: false, currentCount: 0 },
  "after-prayer": { completed: false, currentCount: 0 },
  sleep: { completed: false, currentCount: 0 },
  general: { completed: false, currentCount: 0 },
};

// User Islamic settings
export const mockUserIslamicSettings: UserIslamicSettings = {
  userId: "u_01",
  location: {
    city: "القاهرة",
    country: "مصر",
    latitude: 30.0444,
    longitude: 31.2357,
    timezone: "Africa/Cairo",
  },
  calculationMethod: "رابطة العالم الإسلامي",
  madhab: "shafi",
  prayerNotifications: true,
  adhanEnabled: true,
  reminderMinutes: 10,
  morningAdhkarReminder: true,
  eveningAdhkarReminder: true,
  sleepAdhkarReminder: true,
  quranDailyTarget: 10,
};