-- 1.2F Verified Egyptian Education Taxonomy Seed (idempotent)
INSERT INTO public.education_stages (id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), 'Primary', 'PRIMARY', 1, now(), now() WHERE NOT EXISTS (SELECT 1 FROM public.education_stages WHERE code = 'PRIMARY');
INSERT INTO public.education_stages (id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), 'Preparatory', 'PREPARATORY', 2, now(), now() WHERE NOT EXISTS (SELECT 1 FROM public.education_stages WHERE code = 'PREPARATORY');
INSERT INTO public.education_stages (id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), 'Secondary', 'SECONDARY', 3, now(), now() WHERE NOT EXISTS (SELECT 1 FROM public.education_stages WHERE code = 'SECONDARY');
INSERT INTO public.education_stages (id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), 'Baccalaureate', 'BACCALAUREATE', 4, now(), now() WHERE NOT EXISTS (SELECT 1 FROM public.education_stages WHERE code = 'BACCALAUREATE');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 1', 'P1', 1, now(), now() FROM public.education_stages s WHERE s.code = 'PRIMARY' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'P1');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 2', 'P2', 2, now(), now() FROM public.education_stages s WHERE s.code = 'PRIMARY' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'P2');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 3', 'P3', 3, now(), now() FROM public.education_stages s WHERE s.code = 'PRIMARY' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'P3');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 4', 'P4', 4, now(), now() FROM public.education_stages s WHERE s.code = 'PRIMARY' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'P4');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 5', 'P5', 5, now(), now() FROM public.education_stages s WHERE s.code = 'PRIMARY' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'P5');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 6', 'P6', 6, now(), now() FROM public.education_stages s WHERE s.code = 'PRIMARY' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'P6');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 1', 'PREP1', 1, now(), now() FROM public.education_stages s WHERE s.code = 'PREPARATORY' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'PREP1');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 2', 'PREP2', 2, now(), now() FROM public.education_stages s WHERE s.code = 'PREPARATORY' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'PREP2');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 3', 'PREP3', 3, now(), now() FROM public.education_stages s WHERE s.code = 'PREPARATORY' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'PREP3');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 1', 'SEC_GEN_1', 1, now(), now() FROM public.education_stages s WHERE s.code = 'SECONDARY' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'SEC_GEN_1');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 2', 'SEC_GEN_2', 2, now(), now() FROM public.education_stages s WHERE s.code = 'SECONDARY' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'SEC_GEN_2');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 3', 'SEC_GEN_3', 3, now(), now() FROM public.education_stages s WHERE s.code = 'SECONDARY' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'SEC_GEN_3');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 1', 'BACC_1', 1, now(), now() FROM public.education_stages s WHERE s.code = 'BACCALAUREATE' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'BACC_1');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 2', 'BACC_2', 2, now(), now() FROM public.education_stages s WHERE s.code = 'BACCALAUREATE' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'BACC_2');
INSERT INTO public.education_grades (id, stage_id, name, code, order_index, created_at, updated_at) SELECT gen_random_uuid(), s.id, 'Grade 3', 'BACC_3', 3, now(), now() FROM public.education_stages s WHERE s.code = 'BACCALAUREATE' AND NOT EXISTS (SELECT 1 FROM public.education_grades WHERE code = 'BACC_3');
INSERT INTO public.education_tracks (id, stage_id, grade_id, name, code, created_at, updated_at) SELECT gen_random_uuid(), s.id, g.id, 'Medicine & Life Sciences', 'MED', now(), now() FROM public.education_stages s JOIN public.education_grades g ON g.stage_id = s.id WHERE s.code = 'BACCALAUREATE' AND g.code = 'BACC_3' AND NOT EXISTS (SELECT 1 FROM public.education_tracks WHERE code = 'MED');
INSERT INTO public.education_tracks (id, stage_id, grade_id, name, code, created_at, updated_at) SELECT gen_random_uuid(), s.id, g.id, 'Engineering & Computer Science', 'ENG', now(), now() FROM public.education_stages s JOIN public.education_grades g ON g.stage_id = s.id WHERE s.code = 'BACCALAUREATE' AND g.code = 'BACC_3' AND NOT EXISTS (SELECT 1 FROM public.education_tracks WHERE code = 'ENG');
INSERT INTO public.education_tracks (id, stage_id, grade_id, name, code, created_at, updated_at) SELECT gen_random_uuid(), s.id, g.id, 'Business', 'BUS', now(), now() FROM public.education_stages s JOIN public.education_grades g ON g.stage_id = s.id WHERE s.code = 'BACCALAUREATE' AND g.code = 'BACC_3' AND NOT EXISTS (SELECT 1 FROM public.education_tracks WHERE code = 'BUS');
INSERT INTO public.education_tracks (id, stage_id, grade_id, name, code, created_at, updated_at) SELECT gen_random_uuid(), s.id, g.id, 'Humanities / Arts', 'HUM', now(), now() FROM public.education_stages s JOIN public.education_grades g ON g.stage_id = s.id WHERE s.code = 'BACCALAUREATE' AND g.code = 'BACC_3' AND NOT EXISTS (SELECT 1 FROM public.education_tracks WHERE code = 'HUM');
-- Verify counts (admin execution)
SELECT 'stages', COUNT(*) FROM public.education_stages WHERE code IN ('PRIMARY','PREPARATORY','SECONDARY','BACCALAUREATE');
SELECT 'grades' FROM public.education_grades WHERE stage_id IN (SELECT id FROM public.education_stages WHERE code IN ('PRIMARY','PREPARATORY','SECONDARY','BACCALAUREATE')) GROUP BY stage_id;
SELECT 'tracks' FROM public.education_tracks WHERE stage_id IN (SELECT id FROM public.education_stages WHERE code='BACCALAUREATE');
